# version: "3.7"

services:
  redis:
    container_name: redis
    image: docker.io/valkey/valkey:8-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    networks:
#      - searxng
      - default
    volumes:
      - valkey-data2:/data
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    networks:
#      - searxng
      - default
    ports:
      - "8080:8080"
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
#      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
      - UWSGI_WORKERS=${SEARXNG_UWSGI_WORKERS:-4}
      - UWSGI_THREADS=${SEARXNG_UWSGI_THREADS:-4}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.search.rule=Host(`search.truc.fr`)"
      - "traefik.http.routers.search.entrypoints=websecure"
      - "traefik.http.routers.search.tls=true"
      - "traefik.http.routers.search.middlewares=authelia@file"
      - "traefik.http.services.search.loadbalancer.server.port=8080"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

# networks:
#   searxng:
networks:
  default:
    external: true
    name: authelia_network

volumes:
#  caddy-data:
#  caddy-config:
  valkey-data2:
